[tool.poetry]
name = 'fastdoc'
version = '0.1.0'
description = 'FastAPI doc-coverage scanner + dashboard'
authors = ['Bartosz Kobylinski']

[tool.poetry.dependencies]
python = '^3.10'
typer = '^0.16.0'
pandas = "^2.3"
streamlit = "^1.46"
openai = "^0.27.0"